### ISSUE TITLE
Homebridge WOL

### ISSUE THREAD

**Issue by Knobiwahn** [AlexGustafsson/AlexGustafsson#1]
was mach ich falsch? what did i wrong

[9/26/2021, 11:07:09 AM] [BiggBobb] NetworkDevice shutdown cycle started for "BiggBobb" (192.168.10.59)
[9/26/2021, 11:07:09 AM] [BiggBobb] NetworkDevice "BiggBobb" (192.168.10.59) went from status "Online" to "Shutting Down"
[9/26/2021, 11:07:09 AM] [BiggBobb] Attempting to shut down "BiggBobb" (192.168.10.59) using "net"
[9/26/2021, 11:07:09 AM] [BiggBobb] An error occured while trying to shut down "BiggBobb" (192.168.10.59): Error: Command failed: net rpc shutdown --ipaddress 192.168.10.59 --user admin%admin
/bin/sh: net: not found

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'net rpc shutdown --ipaddress 192.168.10.59 --user admin%admin',
  stdout: '',
  stderr: '/bin/sh: net: not found\n'
}
[9/26/2021, 11:07:09 AM] [BiggBobb] Waiting for shutdown grace time (15000ms) for "BiggBobb" (192.168.10.59)

**Comment by AlexGustafsson** [comment]
Hi! I think you’re a bit lost, but I see you find your way to the repository’s issues: https://github.com/AlexGustafsson/homebridge-wol/issues/172. Closing.
